name: Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 17.x]
    
    steps:
      - name: Check out repository.
        uses: actions/checkout@v2
      - name: Install operating-system dependencies.
        run: |
          supo apt update
          sudo apt libpam0g-dev
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}